<?php
/**
 * @link https://github.com/yiiviet/yii2-esms
 * @copyright Copyright (c) 2017 Yii Viet
 * @license [New BSD License](http://www.opensource.org/licenses/bsd-license.php)
 */


namespace yiiviet\esms;
use vxm\gatewayclients\RequestData;
use yii\httpclient\Client as HttpClient;

/**
 * Lớp SMS
 *
 * @author Vuong Minh <vuongxuongminh@gmail.com>
 * @since 1.0
 */
class SMS extends Gateway
{

    public function getBaseUrl(): string
    {
        return parent::getBaseUrl(); // TODO: Change the autogenerated stub
    }


    protected function sendInternal(RequestData $requestData, HttpClient $httpClient): array
    {
        // TODO: Implement sendInternal() method.
    }

}
